---
title: "Normalize zip codes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

A function that tries its hardest to take any reasonable input and generate a five-digit character string zip code.

```{r}
normalize_zip <- function(zipcode) {
  capture_group <- function(data, regex) {
    tibble(data) %>%
      extract(col = data, into = "captured", regex = regex) %>%
      pull(captured)
  }

  # input can be numeric or character
  # we need to treat these differently
  if (is.character(zipcode)) {
    zipcode <- ifelse( # remove parts after - if there is one
      grepl("^\\s*(\\d+)-.*", zipcode),
      capture_group(zipcode, "^\\s*(\\d+)-.*"),
      zipcode
    )
      
    nas <- is.na(zipcode)
    # remove trailing four digits if too long
    zipcode <- ifelse(
      nchar(zipcode) > 5, 
      capture_group(zipcode, "(.*)\\d\\d\\d\\d"),
      zipcode
    )
    # pad with zeros if too short
    zipcode <- ifelse(
      nchar(zipcode) < 5,
      sprintf("%05i", as.numeric(zipcode)),
      zipcode
    )
    # restor NA values
    zipcode[nas] <- NA_character_
    return(zipcode)
  }
  
  if (!isTRUE(is.numeric(zipcode))) {
    stop("input must be character or numeric")
  }
  
  zipcode <- ifelse(
    zipcode > 100000,
    floor(zipcode/10000),
    zipcode
  )
  # keep position of NAs to recover later
  nas <- is.na(zipcode)
  
  # pad with zeros where needed
  zipcode <- sprintf("%05i", as.numeric(zipcode))
  zipcode[nas] <- NA_character_
  
  zipcode
}
```

Testing the code

```{r}
normalize_zip(
  c("1", "10", "101", "3420", "34205", "943032", "2340594", "23495420", "999999999", NA)
)

normalize_zip(
  c("1", "10", "101", "3420", "34205", "3-4205", "94-3032", "234-0594", "2349-5420", "99999-9999", NA)
)

normalize_zip(
  c(1, 10, 101, 3420, 34205, 943032, 2340594, 23495420, 999999999, NA)
)

# check that wrong input generates errors
testthat::expect_error(
  normalize_zip(NULL),
  "input must be character or numeric"
)
testthat::expect_error(
  normalize_zip(list()),
  "input must be character or numeric"
)
```
